[versions]
kotlin = "2.2.21"
scala = "3.6.3"
asm = "9.9"

[libraries]
scala3-library = { group = "org.scala-lang", name = "scala3-library_3", version.ref = "scala" }

asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version.ref = "asm" }
asm-util = { group = "org.ow2.asm", name = "asm-util", version.ref = "asm" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
asm-analysis = { group = "org.ow2.asm", name = "asm-analysis", version.ref = "asm" }

[bundles]
asm = ["asm", "asm-tree", "asm-util", "asm-commons", "asm-analysis"]